export const GET_LESSIONS_REQUEST = "GET_LESSIONS_REQUEST";
export const GET_LESSIONS_SUCCESS = "GET_LESSIONS_SUCCESS";
export const GET_LESSIONS_FAILURE = "GET_LESSIONS_FAILURE";

export const GET_LESSION_REQUEST = "GET_LESSION_REQUEST";
export const GET_LESSION_SUCCESS = "GET_LESSION_SUCCESS";
export const GET_LESSION_FAILURE = "GET_LESSION_FAILURE";

export const CREATE_LESSIONS_REQUEST = "CREATE_LESSIONS_REQUEST";
export const CREATE_LESSIONS_SUCCESS = "CREATE_LESSIONS_SUCCESS";
export const CREATE_LESSIONS_FAILURE = "CREATE_LESSIONS_FAILURE";

export const DELETE_LESSIONS_REQUEST = "DELETE_LESSIONS_REQUEST";
export const DELETE_LESSIONS_SUCCESS = "DELETE_LESSIONS_SUCCESS";
export const DELETE_LESSIONS_FAILURE = "DELETE_LESSIONS_FAILURE";

export const UPDATE_LESSION_REQUEST = "UPDATE_LESSION_REQUEST";
export const UPDATE_LESSION_SUCCESS = "UPDATE_LESSION_SUCCESS";
export const UPDATE_LESSION_FAILURE = "UPDATE_LESSION_FAILURE";