export const GET_TYPEBLOG_REQUEST = "GET_TYPEBLOG_REQUEST";
export const GET_TYPEBLOG_SUCCESS = "GET_TYPEBLOG_SUCCESS";
export const GET_TYPEBLOG_FAILURE = "GET_TYPEBLOG_FAILURE";

export const CREATE_TYPEBLOG_REQUEST = "CREATE_TYPEBLOG_REQUEST";
export const CREATE_TYPEBLOG_SUCCESS = "CREATE_TYPEBLOG_SUCCESS";
export const CREATE_TYPEBLOG_FAILURE = "CREATE_TYPEBLOG_FAILURE";

export const UPDATE_TYPEBLOG_REQUEST = "UPDATE_TYPEBLOG_REQUEST";
export const UPDATE_TYPEBLOG_SUCCESS = "UPDATE_TYPEBLOG_SUCCESS";
export const UPDATE_TYPEBLOG_FAILURE = "UPDATE_TYPEBLOG_FAILURE";

export const DELETE_TYPEBLOG_REQUEST = "DELETE_TYPEBLOG_REQUEST";
export const DELETE_TYPEBLOG_SUCCESS = "DELETE_TYPEBLOG_SUCCESS";
export const DELETE_TYPEBLOG_FAILURE = "DELETE_TYPEBLOG_FAILURE";